#SECRET_KEY = "JIKEXUEYUAN"
#MONGODB_SETTINGS = {'DB': 'todo'}
#WTF_CSRF_ENABLED = False


SQLALCHEMY_DATABASE_URI = "mysql://root:kejie@1234@121.42.165.46:3306/db_aipaimingTest"
SQLALCHEMY_TRACK_MODIFICATIONS=True